### ISSUE TITLE
serial update do not work

### ISSUE THREAD

**Issue by tomaszduda23** [intercreate/smpclient#22]
I've checked 2.0.1 and serial update do not work. It seems that  following is missing.
```python

    async def send(self, data: bytes) -> None:
        logger.debug(f"Sending {len(data)} bytes")
        # line cannot be bigger than 128 bytes by default
        # https://github.com/zephyrproject-rtos/zephyr/blob/076c0df3d8a878e4457c1d831704cd33b9ead6d3/drivers/console/uart_mcumgr.c#L101
        # https://github.com/zephyrproject-rtos/zephyr/blob/076c0df3d8a878e4457c1d831704cd33b9ead6d3/drivers/console/Kconfig#L204
        for packet in smppacket.encode(data, line_length=128):
```

**Comment by JPHutchins** [comment]
Are you updating from within MCUBoot or from within the application?

If using MCUBoot to upload, set these KConfigs:
```
BOOT_LINE_BUFS=2
CONFIG_BOOT_MAX_LINE_INPUT_LEN=4096
CONFIG_BOOT_SERIAL_MAX_RECEIVE_SIZE=8192
```

If using the application, set these KConfigs, though I haven't tried serial transport from an application yet:
```
MCUMGR_TRANSPORT_NETBUF_SIZE=4098
MCUMGR_TRANSPORT_UART_MTU=4096
```

I'll add a serial example to the folder ASAP.

If you're OK with the slow transfers and only want the compatibility, then you need to set the MTU to match the one that you are using - 128, I think - when you initialize the client, e.g.:
```python
client = SMPClient(SMPSerialTransport(mtu=128), "/dev/ttyACM0")
```

Default MTU is defined here: https://github.com/intercreate/smpclient/blob/0f47207c8d44b843a599d23ff7dd202dcdac25c2/smpclient/transport/serial.py#L69

**Comment by JPHutchins** [comment]
I forgot about another bug in Zephyr's SMP server implementation.  It requires that the first 32 bytes of the image are included in the first packet.  This is not a requirement of the protocol and is a bug.  It will fail for small MTUs when the SHA is included because it prevents all 32 bytes from being included in the first packet.  Another problem is that know SMP server I've seen so far even uses the SHA - probably a good idea to check that the data that's uploaded is correct!

I'll need to add a default argument to the upload method that allows the user to not send the SHA.

```python
    async def upload(
        self, image: bytes, slot: int = 0, upgrade: bool = False, use_sha: bool = True
    ) -> AsyncIterator[int]:
        """Iteratively upload an `image` to `slot`, yielding the offset."""

        if self._transport.max_unencoded_size < 23:
            raise Exception("Upload requires an MTU >=23.")

        response = await self.request(
            self._maximize_packet(
                ImageUploadWrite(
                    off=0,
                    data=b"",
                    image=slot,
                    len=len(image),
                    sha=sha256(image).digest() if use_sha else None,
                    upgrade=upgrade,
                ),
                image,
            )
        )
```

**Comment by JPHutchins** [comment]
Based on the integration tests that I have written, I can see uploads working to a Zephyr app at MTU=128 so long as the SHA is not included in the initial upload request.  I have been unable to get uploads to proceed at MTU > 128 and probably need to attach a debugger to the FW to understand why it is not responding when the MTU is greater.

My latest config is
```
CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=4098
CONFIG_MCUMGR_TRANSPORT_UART_MTU=4096
CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=6000
CONFIG_MCUMGR_TRANSPORT_NETBUF_COUNT=2
```

This config does still work with MTU=128 but not with anything larger.  Very fishy!

At MTU 128 I am getting less than 4KBps.  In MCUBoot (AKA Zephyr) with MTU 4096 I get 55KBps.  So I'd like to resolve this.

**Comment by JPHutchins** [comment]
MMM, may have found it...
CONFIG_UART_MCUMGR_RX_BUF_SIZE=128
CONFIG_UART_MCUMGR_RX_BUF_COUNT=2

**Comment by JPHutchins** [comment]
Yep, gottem.

```
Uploaded 75,267 / 75,267 Bytes | 46.14 KB/s
```

Setting the NETBUF for MCUMGR Transport without also setting that UART_MCUMGR_RX_BUF_SIZE should cause a compile time error, or at LEAST a runtime error.  Here's the working config:

```
CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=4098
CONFIG_MCUMGR_TRANSPORT_UART_MTU=4096
CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=6000
CONFIG_MCUMGR_TRANSPORT_NETBUF_COUNT=2
CONFIG_UART_MCUMGR_RX_BUF_SIZE=4098
CONFIG_UART_MCUMGR_RX_BUF_COUNT=2
```

Very uncertain about what the exact values should be.  Generally no more than 1 buffer should be required for "well behaved" clients, not sure what the design goals was.

**Comment by tomaszduda23** [comment]
I can change buffers size on zephyr side. It should work with default settings though since it will be most reliable for most user. I checked other mcumgr clients and it has following settings:
```python
smp_client = SMPClient(SMPSerialTransport(mtu=256), host)
```
and
```python
    async def send(self, data: bytes) -> None:
        logger.debug(f"Sending {len(data)} bytes")
        # line cannot be bigger than 128 bytes by default
        # https://github.com/zephyrproject-rtos/zephyr/blob/076c0df3d8a878e4457c1d831704cd33b9ead6d3/drivers/console/uart_mcumgr.c#L101
        # https://github.com/zephyrproject-rtos/zephyr/blob/076c0df3d8a878e4457c1d831704cd33b9ead6d3/drivers/console/Kconfig#L204
        for packet in smppacket.encode(data, line_length=128):
``
MTU size and line size can be different.

**Comment by tomaszduda23** [comment]
If you could expose both values in API. It can be decided if speed or reliability is more important for an user.

**Comment by JPHutchins** [comment]
> It should work with default settings though.

OK, I finally agree on this point.  I will be testing out a config that sets MTU 256 and line_length 128 to match what I see here:

https://github.com/zephyrproject-rtos/zephyr/blob/ea29ef36bbedeacd171199d6feea5e699fa64447/drivers/console/Kconfig#L202-L218

> If you could expose both values in API. It can be decided if speed or reliability is more important for an user.

The distinction should be between speed and compatibility, not reliability.  The faster transfers are no less reliable, but they do require MCU's with sufficient RAM for the larger buffers.

> MTU size and line size can be different.

Yeah, I'm trying to simplify that because I'm not sure that it's useful.  We can think of the MTU as how much buffer is available on the server.  The line length is the "size of one packet".  But why a distinction?

Without getting into how MCUBoot's SMP server handles it, which is different, here's what I see in a Zephyr application server:

https://github.com/zephyrproject-rtos/zephyr/blob/ea29ef36bbedeacd171199d6feea5e699fa64447/drivers/console/Kconfig#L202-L218

Statically allocates here

https://github.com/zephyrproject-rtos/zephyr/blob/ea29ef36bbedeacd171199d6feea5e699fa64447/include/zephyr/drivers/console/uart_mcumgr.h#L23-L30

and here

https://github.com/zephyrproject-rtos/zephyr/blob/ea29ef36bbedeacd171199d6feea5e699fa64447/drivers/console/uart_mcumgr.c#L34-L35

To get the total static allocation of CONFIG_UART_MCUMGR_RX_BUF_SIZE * CONFIG_UART_MCUMGR_RX_BUF_COUNT

So, 256 by default.

Then CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE  * CONFIG_MCUMGR_TRANSPORT_NETBUF_COUNT space is allocated again

https://github.com/zephyrproject-rtos/zephyr/blob/ea29ef36bbedeacd171199d6feea5e699fa64447/subsys/mgmt/mcumgr/transport/src/smp.c#L42C1-L44

It feels like a lot of this infrastructure is in place to handle multiple/concurrent SMP requests which seems unnecessary.

TBH, I see a getter for the CONFIG_MCUMGR_TRANSPORT_UART_MTU set to the function pointer `get_mtu`, but I cannot find anywhere that the function is called.  It may be dead code.

So how does line length and "mtu" fit into all of this?

Terminology in the MCUBoot implementation is perhaps more clear:

https://github.com/mcu-tools/mcuboot/blob/45d379e715d82ae71ce2bb42882769a4cf4428e4/boot/zephyr/Kconfig.serial_recovery#L75-L97

So BOOT_MAX_LINE_INPUT_LEN would be the line length, 128
BOOT_LINE_BUFS could be set to 2 to match Zephyr app
And BOOT_SERIAL_MAX_RECEIVE_SIZE could be set to CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE  * CONFIG_MCUMGR_TRANSPORT_NETBUF_COUNT to match Zephyr app.

I see the point in fragmenting a packet of size 2475 for the BLE transport.  I do not see the point in fragmenting the serial transport packets.  Why not simply contain the entire packet in one line and avoid the use of the continuation delimiter altogether?

**Comment by tomaszduda23** [comment]
There are some strange architecture decision on mcumgr server side. The main problem is that server just ignore too long line silently. If there would be an error message any value would be fine.
It is very frustrating (since it requires a lot of time) to setup debugger and check the code just to find out that there is mismatch of buffer size on client and server side (the transfer just get stuck in such case).
Of course I can set any value you like in my project. I can imagine though that other people would like to use your project with default values (there are cases when you cannot just flash bootloader which you already have).
I would take lower speed if it works out of the box for the most users.

**Comment by JPHutchins** [comment]
> mismatch of buffer size on client and server side (the transfer just get stuck in such case)

This is a good point.  There are errors defined for this sorta thing, so it shouldn't be too bad for the SMP server to return an error.

For BLE, the header itself should trigger an error if the header is showing a packet that's too big to fit in the buffers.

For serial, it the server waits for `\n` - if the buffer is out of space before it gets `\n` it should return an error.

**Comment by tomaszduda23** [comment]
I check version 3.2.0. It looks that all those works:
1. serial update with default setting
2. BLE disconnect
3. upload timeouts
:+1:

**Comment by JPHutchins** [comment]
> I check version 3.2.0. It looks that all those works:
> 
> 1. serial update with default setting
> 2. BLE disconnect
> 3. upload timeouts

Thank you for all of the help!  Feeling much more confident in the system now.  Still lots to do but I hope that your work is unblocked.
